In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3]

In [3]:
type(lista)

list

In [4]:
np.array(lista)

array([1, 2, 3])

In [5]:
a = np.array(lista)

In [6]:
type(a)

numpy.ndarray

In [7]:
lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(lista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Arange

In [53]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### Zeros e Uns

In [46]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros([5, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(2)

array([1., 1.])

In [16]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [17]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [48]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Linspace

In [20]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [21]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### Rand

In [23]:
np.random.rand(5)

array([0.97003097, 0.47241111, 0.20934232, 0.60542213, 0.80152412])

In [55]:
np.random.rand(5) * 100

array([18.52752182, 63.46351183,  8.82306028, 60.4915705 , 55.94138799])

In [25]:
np.random.rand(5, 5)

array([[0.16428208, 0.60795706, 0.7421556 , 0.15317881, 0.96332936],
       [0.20993714, 0.94181705, 0.32769915, 0.98624375, 0.1289465 ],
       [0.39730354, 0.39164495, 0.98872667, 0.56458797, 0.02192876],
       [0.33731882, 0.33942764, 0.53844489, 0.38632418, 0.18903475],
       [0.59481733, 0.17327833, 0.77829692, 0.24175376, 0.42182606]])

### Randn

In [26]:
np.random.randn(5)

array([ 0.44484714,  0.48503854,  1.27576668, -0.55376431,  0.49668879])

In [27]:
np.random.randn(5, 5)

array([[-0.62713068, -0.47942751,  0.05706811,  1.64645476,  1.59981857],
       [ 0.69713474,  0.39999793, -1.67833255,  0.59432003,  0.27821338],
       [ 0.18848826, -1.60033778,  1.12653801, -0.64875468,  0.65867335],
       [-0.35237575, -0.69350899,  0.21603956,  1.15141289, -0.64027229],
       [ 0.08857437,  0.0884009 ,  0.3232054 , -0.65939651,  0.91204246]])

### Randint

In [30]:
np.random.randint(1, 10)

8

In [31]:
np.random.randint(0, 100, 10)

array([99, 57, 44, 97, 75, 61, 92, 36, 79, 77])

### Reshape

In [32]:
arr = np.random.rand(25)

In [33]:
arr

array([0.36427544, 0.06587073, 0.48865735, 0.60830737, 0.87020245,
       0.24424017, 0.25036908, 0.10931799, 0.83273316, 0.82993801,
       0.10001021, 0.89829845, 0.51996496, 0.88927347, 0.76702305,
       0.9616531 , 0.83885777, 0.15121177, 0.03330068, 0.36911412,
       0.07906954, 0.30713217, 0.59094475, 0.30220724, 0.83849445])

In [34]:
arr.shape

(25,)

In [35]:
arr

array([0.36427544, 0.06587073, 0.48865735, 0.60830737, 0.87020245,
       0.24424017, 0.25036908, 0.10931799, 0.83273316, 0.82993801,
       0.10001021, 0.89829845, 0.51996496, 0.88927347, 0.76702305,
       0.9616531 , 0.83885777, 0.15121177, 0.03330068, 0.36911412,
       0.07906954, 0.30713217, 0.59094475, 0.30220724, 0.83849445])

In [36]:
arr = arr.reshape((5, 5))

In [37]:
arr

array([[0.36427544, 0.06587073, 0.48865735, 0.60830737, 0.87020245],
       [0.24424017, 0.25036908, 0.10931799, 0.83273316, 0.82993801],
       [0.10001021, 0.89829845, 0.51996496, 0.88927347, 0.76702305],
       [0.9616531 , 0.83885777, 0.15121177, 0.03330068, 0.36911412],
       [0.07906954, 0.30713217, 0.59094475, 0.30220724, 0.83849445]])

In [38]:
 arr.shape

(5, 5)

### max, min, argmax e argmin

In [39]:
arr

array([[0.36427544, 0.06587073, 0.48865735, 0.60830737, 0.87020245],
       [0.24424017, 0.25036908, 0.10931799, 0.83273316, 0.82993801],
       [0.10001021, 0.89829845, 0.51996496, 0.88927347, 0.76702305],
       [0.9616531 , 0.83885777, 0.15121177, 0.03330068, 0.36911412],
       [0.07906954, 0.30713217, 0.59094475, 0.30220724, 0.83849445]])

In [41]:
arr.max()

0.961653101095833

In [42]:
arr.min()

0.033300676683819974

In [43]:
arr.argmax()

15

In [44]:
arr.argmin()

18